### PR TITLE
add statsbomb json-to-csv tool link in readme

### PR DESCRIPTION
**Pull request by imrankhan17**

### CODE REVIEW

**Comment by imrankhan17** [comment]
@devinpleuler thanks for considering my pull request - can I get a reason why it wasn't merged?

**Comment by devinpleuler** [comment]
@imrankhan17 Thank you for your recommendation. I cover some data-flattening techniques in one of the existing notebooks. Also, I wouldn't want to link to a url that looks temporary.

**Comment by imrankhan17** [comment]
@devinpleuler This is an alternative way to achieve what you cover in your notebooks, so I think only adds to the repo.  It's great for beginners who might want to go straight into working with CSV's initially.  In fact the tool's already gotten good feedback from members of the analytics community who have used it.

The application is hosted on AWS - it's had the same URL for over a year and will continue to do so for as long as I have my AWS account.  I just haven't gotten around to purchasing a custom domain for it.

**Comment by devinpleuler** [comment]
If you want to include a link to the github repository for the parser, I'm happy to add that.

**Pull request closed without merging**
